apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: aspnetcore-pod
  template:
    metadata:
      labels:
        app: aspnetcore-pod
    spec:
      containers:
      - name: hello-aspnetcore-container
        image: arash01.azurecr.io/aspnetcore:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
