apiVersion : apps/v1
kind: Deployment
metadata:
  name: aspnetcoretest 
  namespace: development
spec:
  selector:
    matchLabels:
      app: aspnetcoretest
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetcoretest 
    spec:
      containers:
        - name: aspnetcoretest 
          image: arash01.azurecr.io/aspnetcoretest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
