apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: arashaspnetcore 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: arashaspnetcore 
    spec:
      containers:
        - name: arashaspnetcore 
          image: arash01.azurecr.io/arashaspnetcore
          ports:
          - containerPort: 80