apiVersion: v1
kind: Service
metadata:
    name: aspnetcoretest
    namespace: #{namespace-key}#
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: aspnetcoretest